monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.usb-Macronix_Razer_Barracuda_2.4_1234-00"
      }
    ]

    actions = {
      update-props = {
        api.alsa.soft-mixer = true
      }
    }
  }
]
